//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDangKyMonHoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class ChiTietChuongTrinhHoc
    {
        public int idChiTietCTH { get; set; }
        [DisplayName("id Chương Trình")]
        public int idChuongTrinh { get; set; }
        [DisplayName("Mã Môn Học")]
        public string MaMH { get; set; }

        [DisplayName("Chương Trình Học")]
        public virtual ChuongTrinhHoc ChuongTrinhHoc { get; set; }

        [DisplayName("Môn Học")]
        public virtual MonHoc MonHoc { get; set; }
    }
}
