//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDangKyMonHoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Configuration;

    public partial class DotDangKy
    {
        [DisplayName("Mã Đợt Đăng Ký")]
        public int idDotDangKy { get; set; }
        [DisplayName("Học Kỳ Chương Trình")]
        [Range(1,8)]
        public int HocKyChuongTrinh { get; set; }
        [DisplayName("Mã Khoa")]
        public string MaKhoa { get; set; }
        [DisplayName("Khóa Học")]
        public int KhoaHoc { get; set; }
        [DisplayName("Ngày Bắt Đầu")]
        public System.DateTime NgayBatDau { get; set; }
        [DisplayName("Ngày Kết Thúc")]
        public System.DateTime NgayKetThuc { get; set; }

        [DisplayName("Tên Khoa")]
        public virtual Khoa Khoa { get; set; }
    }
}
