//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDangKyMonHoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class GiaoVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GiaoVien()
        {
            this.LopHPs = new HashSet<LopHP>();
        }
        [DisplayName("Mã Giáo Viên")]
        public string MaGV { get; set; }
        [DisplayName("Tên Giáo Viên")]
        public string TenGV { get; set; }
        [DisplayName("Mã Khoa")]
        public string MaKhoa { get; set; }
        [DisplayName("Ngày Sinh")]
        public string NgaySinh { get; set; }
        [DisplayName("Giới Tính")]
        public string GioiTinh { get; set; }
        [DisplayName("Email")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        [DisplayName("Địa Chỉ")]
        public string DiaChi { get; set; }
        [DisplayName("Số Điện Thoại")]
        public string SDT { get; set; }
        [DisplayName("Khoa")]
        public virtual Khoa Khoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LopHP> LopHPs { get; set; }
    }
}
