//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDangKyMonHoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class LopHP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LopHP()
        {
            this.PhieuDangKyHocs = new HashSet<PhieuDangKyHoc>();
        }

        [DisplayName("Mã LHP")]
        public string MaLHP { get; set; }
        [DisplayName("Mã Giáo Viên")]
        public string MaGV { get; set; }
        [DisplayName("Mã Môn Học")]
        public string MaMH { get; set; }
        [DisplayName("Mã Khoa")]
        public string MaKhoa { get; set; }
        [DisplayName("Tiết Học")]
        public string TietHoc { get; set; }
        [DisplayName("Phòng Học")]
        public string PhongHoc { get; set; }
        [DisplayName("Thứ")]
        public string Thu { get; set; }
        [DisplayName("Sĩ Số Tối Đa")]
        public string SiSoMax { get; set; }
        [DisplayName("Học Kỳ")]
        public string HocKy { get; set; }
        [DisplayName("Năm Học")]
        public string NamHoc { get; set; }
    
        public virtual GiaoVien GiaoVien { get; set; }
        public virtual MonHoc MonHoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuDangKyHoc> PhieuDangKyHocs { get; set; }
    }
}
