//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDangKyMonHoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiQuanLy
    {
        public string MaNQL { get; set; }
        public string Ten { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
    }
}
