//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDangKyMonHoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class PhieuDangKyHoc
    {
        [DisplayName("Mã Phiếu")]
        public int MaPhieuDangKy { get; set; }
        [DisplayName("Mã LHP")]
        public string MaLHP { get; set; }
        [DisplayName("Mã Sinh Viên")]
        public string MaSV { get; set; }
        [DisplayName("Mã Học Kỳ")]
        public string HocKy { get; set; }
        [DisplayName("Năm Học")]
        public string NamHoc { get; set; }
        [DisplayName("Ngày Đăng Ký")]
        public System.DateTime NgayDangKy { get; set; }

        [DisplayName("Lớp HP")]
        public virtual LopHP LopHP { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
