//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDangKyMonHoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class SinhVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SinhVien()
        {
            this.PhieuDangKyHocs = new HashSet<PhieuDangKyHoc>();
        }
        [DisplayName("Mã Sinh Viên")]
        public string MaSV { get; set; }
        [DisplayName("Mật khẩu")]
        public string Password { get; set; }
        [DisplayName("Tên Sinh Viên")]
        public string TenSV { get; set; }
        [DisplayName("Mã Lớp")]
        public string MaLop { get; set; }
        [DisplayName("Hệ Đào Tạo")]
        public string HeDaoTao { get; set; }
        [DisplayName("Ngày Sinh")]
        public string NgaySinh { get; set; }
        [DisplayName("Giới Tính")]
        public string GioiTinh { get; set; }
        [DisplayName("Địa Chỉ")]
        public string DiaChi { get; set; }
        [DisplayName("Số Điện Thoại")]
        public string SDT { get; set; }

        [DisplayName("Lớp")]
        public virtual Lop Lop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuDangKyHoc> PhieuDangKyHocs { get; set; }
    }
}
